### ISSUE TITLE
Agence Pessoa Desenvolvedora @Inphonex

### ISSUE THREAD

**Issue by Julia-HeadHunting** [elug-ce/oportunidades#10]
## 📝  Buscamos profissionais com nível de senioridade Pleno ou Sênior

💡 A InPhonex é uma empresa americana fundada em 2003 para fornecer serviços de telefonia sobre IP (VoIP) para usuários residenciais, pequenas, médias e grandes empresas. Empresa pioneira na oferta de sua plataforma completa de VoIP como um produto white-label (PaaS), oferecendo serviços para mais de 100 países

### Requisitos

- Angular.JS (versão 1.6);
- Angular + (outras versões);
- React.JS;
- React Native;
- Javascript;
- HTML5;
-  CSS3;
- Consumo de APIs;
- SASS;
- Typescript;
- Storybook;
- React Hooks;

## 👋 Como se candidatar

Envie seu currículo para talentos@agence.com.br  com o título "Front End". Use a oportunidade para nos contar um pouco da sua carreira e experiência Front End, e por quê você se interessou em trabalhar com a gente. :-)

**Comment by joeljuca** [comment]
Olá @Julia-HeadHunting,

Esse espaço é exclusivo para oportunidades Elixir, Erlang e/ou tecnologias BEAM. Para divulgar vagas front end, recomendo o frontendbr/vagas (ele inclusive é bem mais popular que nós):

https://github.com/frontendbr/vagas

**Comment by Julia-HeadHunting** [comment]
Bom dia, muito obrigadaa!!
E me perdõe, não entendi muito do site rsrs
Mas vou pesquisar mais para não acontecer de novo, obrigada!

Att.;

Julia Dória Lazareti
