### ISSUE TITLE
Pessoa Desenvolvedora @ SolFacil

### ISSUE THREAD

**Issue by CamilaFFelix** [elug-ce/oportunidades#11]
A SolFacil é a primeira Fintech a lançar uma plataforma digital de investimentos em energia solar fotovoltaica no Brasil, desde 2018 ela vem revolucionando este mercado, conectando instaladores e consumidores e também sendo uma facilitadora para o financiamento de painéis solares. 

Como parte do time você vai atuar diretamente na criação e evolução do portfólio de produtos e trabalhar diretamente com outros profissionais da área de Back-end, Front-end e Produto com os quais terá a oportunidade de colaborar, aprender e trocar experiências durante esta jornada. A principal linguagem utilizada na empresa é Elixir.

## 📝 Qualificação

REQUISITOS

- Experiência com Elixir, 
- Testes automatizados (unitários e/ou integração)
- Bancos relacionais 
- Git

## 👋 Como se candidatar

Para fazer parte desta revolução é só clicar neste link: https://bit.ly/3zxYzOJ

**Comment by CamilaFFelix** [comment]
@joeljuca tudo bem? Gostaria de avisar que tentei colocar as labels, porém não consegui. Estou começando a fazer postagens agora no GitHub.

**Comment by joeljuca** [comment]
@CamilaFFelix boa noite!

Por enquanto, as labels estão sendo gerenciadas por nós. Não conseguimos dar permissão prós usuários (limitação do GitHub).

Vou por as labels agora.

**Comment by CamilaFFelix** [comment]
Oportunidade Finalizada.
