### ISSUE TITLE
Agence- Pessoa Desenvolvedora Front End @Inphonex

### ISSUE THREAD

**Issue by Julia-HeadHunting** [elug-ce/oportunidades#9]
**TODO: substituir texto-exemplo por descrição da vaga.** Estamos buscando uma pessoa desenvolvedora Elixir para juntar-se ao nosso time de engenharia. Nosso mais novo produto é uma inteligência artificial que toca forró em sanfona, zabumba e triângulo usando braços mecânicos. Feito em Elixir, esse software-músico é capaz de reconhecer e reproduzir com perfeição os melhores hinos forrozeiros da cultura cearense.

## 📝 Qualificação

**TODO: substituir texto-exemplo por descrição do projeto.** Nosso software-músico é escrito em Elixir e Axon. Usamos SQLite para persistência de dados, GRPC para comunicação em rede, e GitHub Actions para CI/CD.

### Requisitos

- Habilidades sólidas em Git, GitHub e GitHub Flow
- Experiência em desenvolvimento back end (mín. 1 ano)
- Experiência em desenvolvimento front end (mín. 1 ano)
- Experiência em desenvolvimento DevOps (mín. 1 ano)
- Experiência em SQL e bancos de dados relacionais
- Experiência em programação funcional
- Experiência em testes de software
- Interesse em trabalhar com Elixir

### Desejáveis

- Experiência com Elixir e/ou Phoenix
- Experiência com WebSockets e/ou Phoenix Channels
- Experiência em integração e entrega contínua (CI/CD)
- Familiaridade com GitHub Actions
- Conhecimentos em Docker e Kubernetes
- Conhecimentos em front-end (React ou Phoenix LiveView)
- Conhecimentos em teoria musical

Se você ficou interessado mas não tem experiência com Elixir, candidate-se mesmo assim! Nós lhe ofereceremos um teste técnico para que demonstre suas habilidades em uma linguagem de sua preferência.

## 👋 Como se candidatar

Envie seu currículo para `oportunidades@caju.computer` com o título "Pessoa Desenvolvedora". Use a oportunidade para nos contar um pouco da sua carreira e experiência em engenharia de software, em Elixir (caso tenha), e por quê você se interessou em trabalhar com a gente. :-)

**Comment by joeljuca** [comment]
Oportunidade inválida.
